name: drug_response_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - pyarrow
  - scikit-learn
  - scipy
  - matplotlib
  - statsmodels
  - pyyaml
  - pip:
      - shap